server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koreaitdb?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: koreait
    password: 0000

mybatis:
  mapper-locations:
     - /mappers/*
